#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 10:46:12 2017

@author: ryanneal
"""
import random

def bogo_sort(L):
    tries = 0
    while not is_sorted(L):
        random.shuffle(L)
        tries += 1
        print(tries)
    return(L)


def is_sorted(L):
    for index in range(len(L) - 1):
        if L[index + 1] < L[index]:
            return False
    return True


a = [3, 5, 1, 6, 27, 8, 9, 10, 2, 15]
print(bogo_sort(a))