#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 12:35:18 2017

@author: ryanneal
"""

def bubble_sort(lst):
    while True:
        swap = False
        for index in range(len(lst) - 1):
            if lst[index] > lst[index + 1]:
                swap = True
                tmp = lst[index]
                lst[index] = lst[index + 1]
                lst[index + 1] = tmp
        if swap == False:
            break
    return lst
    
a = [3, 5, 1, 6, 27, 8, 9, 10, 2, 15]
print(bubble_sort(a))
                