#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 15:25:14 2017

@author: ryanneal
"""

def merge_sort(lst):
    if len(lst) < 2:
        return lst[:]
    else:
        mid = len(lst)//2
        left = merge_sort(lst[:mid])
        right = merge_sort(lst[mid:])
    
    return merge(left, right)
        
def merge(left, right):
    if not left or not right:
        return left or right
    
    i, j = 0, 0
    result = []
    for index in range(len(left) + len(right)):
        if left[i] < right[j]:
            result.append(left[i])
            i+=1
        else:
            result.append(right[j])
            j+=1
        if i == len(left):
            result.extend(right[j:])
            break
        elif j == len(right):
            result.extend(left[i:])
            break
    return(result)

a = [3, 5, 1, 6, 27, 8, 9, 10, 2, 15]
print(merge_sort(a))
    
