#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 12:45:09 2017

@author: ryanneal
"""

def selection_sort(lst):
    spot = 0
    while spot != len(lst):
        for index in range(spot, len(lst)):
            if lst[index] < lst[spot]:
                lst[index], lst[spot] = lst[spot], lst[index]
        spot += 1
    return lst
    
a = [3, 5, 1, 6]        
print(selection_sort(a))